// Auto-generated by scripts/deploy.js on 2026-04-15T19:59:38.331Z.
// Manual edits will be overwritten on the next deploy. To prevent that, set
// SKIP_CONFIG_WRITE=1 in the environment when running the deploy command.
window.MBC_CONFIG = {
  MARKETPLACE_ADDRESS: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
  USDC_ADDRESS:        "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  EXPECTED_CHAIN_ID:   31337,
  EXPECTED_CHAIN_NAME: "Hardhat Local",
};
