/**
 * Deploy script for the MBC Polygon marketplace.
 *
 * On hardhat / localhost it deploys a MockUSDC and uses that address.
 * On Amoy / Polygon it expects USDC_ADDRESS to be set in .env; if it is not
 * set on Amoy we deploy MockUSDC as a fallback (so you can get started without
 * hunting for a faucet).
 *
 * After deployment the script also patches `frontend/config.js` so the static
 * site points at the just-deployed contracts and the correct chain id. Set
 * SKIP_CONFIG_WRITE=1 to suppress that side-effect.
 */
const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

const CHAIN_META = {
  hardhat:   { chainId: 31337, label: "Hardhat Local" },
  localhost: { chainId: 31337, label: "Hardhat Local" },
  amoy:      { chainId: 80002, label: "Polygon Amoy" },
  polygon:   { chainId: 137,   label: "Polygon" },
};

function writeFrontendConfig({ marketplace, usdc, chainId, chainName }) {
  const configPath = path.resolve(__dirname, "..", "frontend", "config.js");
  const content = `// Auto-generated by scripts/deploy.js on ${new Date().toISOString()}.
// Manual edits will be overwritten on the next deploy. To prevent that, set
// SKIP_CONFIG_WRITE=1 in the environment when running the deploy command.
window.MBC_CONFIG = {
  MARKETPLACE_ADDRESS: ${JSON.stringify(marketplace)},
  USDC_ADDRESS:        ${JSON.stringify(usdc)},
  EXPECTED_CHAIN_ID:   ${chainId},
  EXPECTED_CHAIN_NAME: ${JSON.stringify(chainName)},
};
`;
  fs.writeFileSync(configPath, content);
  console.log(`Patched ${path.relative(process.cwd(), configPath)}`);
}

async function main() {
  const { ethers, network } = hre;
  const [deployer] = await ethers.getSigners();
  console.log(`Network:  ${network.name}`);
  console.log(`Deployer: ${deployer.address}`);
  console.log(`Balance:  ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} native`);

  // ---- USDC ----
  let usdcAddress = process.env.USDC_ADDRESS || "";
  const isLocal = network.name === "hardhat" || network.name === "localhost";
  const isAmoy = network.name === "amoy";

  if (!usdcAddress && (isLocal || isAmoy)) {
    console.log("No USDC_ADDRESS set, deploying MockUSDC...");
    const MockUSDC = await ethers.getContractFactory("MockUSDC");
    const mock = await MockUSDC.deploy();
    await mock.waitForDeployment();
    usdcAddress = await mock.getAddress();
    console.log(`MockUSDC:        ${usdcAddress}`);

    // Mint some test balance to the deployer so they can play immediately
    const tenThousand = 10_000n * 10n ** 6n; // 10_000 mUSDC
    const tx = await mock.mint(deployer.address, tenThousand);
    await tx.wait();
    console.log(`Minted 10,000 mUSDC to deployer`);
  }

  if (!usdcAddress) {
    throw new Error("USDC_ADDRESS is required for this network. Set it in .env.");
  }

  // ---- Marketplace ----
  const Marketplace = await ethers.getContractFactory("ProjectMarketplace");
  const marketplace = await Marketplace.deploy(usdcAddress);
  await marketplace.waitForDeployment();
  const marketplaceAddress = await marketplace.getAddress();

  console.log("");
  console.log("=== Deployment complete ===");
  console.log(`USDC:         ${usdcAddress}`);
  console.log(`Marketplace:  ${marketplaceAddress}`);

  // ---- Patch frontend/config.js ----
  const meta = CHAIN_META[network.name] || { chainId: network.config.chainId, label: network.name };
  if (process.env.SKIP_CONFIG_WRITE === "1") {
    console.log("\nSKIP_CONFIG_WRITE=1 set, not touching frontend/config.js.");
    console.log(`Paste manually:`);
    console.log(`  MARKETPLACE_ADDRESS = "${marketplaceAddress}"`);
    console.log(`  USDC_ADDRESS        = "${usdcAddress}"`);
    console.log(`  EXPECTED_CHAIN_ID   = ${meta.chainId}`);
  } else {
    writeFrontendConfig({
      marketplace: marketplaceAddress,
      usdc: usdcAddress,
      chainId: meta.chainId,
      chainName: meta.label,
    });
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
